apiVersion: v1
kind: Namespace
metadata:
  name: namespace-two
  annotations:
    operator.tekton.dev/prune.keep-since: "2"
    operator.tekton.dev/prune.resources: taskrun, pipelinerun
    operator.tekton.dev/prune.schedule: "*/2 * * * *"    # Tell the operator to prune the resources every two (test-only, increase the elapsed time in production)
    operator.tekton.dev/prune.strategy: keep-since  